title: up-for-grabs.net

exclude:
  - CNAME
  - Gemfile*
  - tests
  - README.md
  - scripts
  - .travis.yml
  - vendor
  - node_modules
  - package.json
  - yarn.lock
  - .eslintrc.json
  - .prettierrc.json
  - docs

github: [metadata]

# DO NOT DELETE THIS
# This is used to build up the array of projects rendered inside a <noscript>
# tag to support browsers which disable JS. For more context check out
# https://github.com/up-for-grabs/up-for-grabs.net/pull/1412 which explains what
# this gives us.
emptyArray: []

